### ISSUE TITLE
Pick a version scheme that makes sense

### ISSUE THREAD

**Issue by AnthonyMastrean** [gregsaab/StructureMap.AutoMocking.NSubstitute#3]
Do you version like StructureMap and imply the version of NSubstitute? Like `StructureMap.AutoMocking.NSubstitute 2.6.1` for the version of this package that supports `StructureMap 2.6.1? How do you indicate which version of NSubstitute it is built against?

**Comment by gregsaab** [comment]
There is no versioning against nsubstitute, it is dynamically loaded at runtime.

**Comment by AnthonyMastrean** [comment]
You're not limited by a specific public contract?

**Comment by gregsaab** [comment]
it finds the first method in Substitute class that has one generic type constraint and uses the given type against it

**Comment by gregsaab** [comment]
which would be Substitute.For<T>()

**Comment by gregsaab** [comment]
For<>() *

**Comment by gregsaab** [comment]
Since there is no dependence now on automocking or substitute versioning (assuming it is >2.6.1), there is no reason to mirror those numbers.
